services:
  server:
    container_name: server-container
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000
      - DATABASE_URL=postgresql+asyncpg://pguser:pgsecret@database:5432/pgdb
      - ENV=production
      - PORT=5000
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database
    volumes:
      - server:/opt/server

  database:
    image: postgres:latest
    container_name: database-container
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgsecret
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  server:
  database:
